version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code/backend:cached
      - ./datasets:/code/datasets:cached
    environment:
      - DOSAGE_FILE_PATH=datasets/dosage.csv

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py:cached
      - ./features:/app/features:cached
      - ./datasets:/app/datasets:cached
    environment:
      - FAST_API_URL=http://backend:8000
    depends_on:
      - backend
